# Generated by Django 3.2.9 on 2021-11-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinksAndPeople', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebida',
            options={'verbose_name': 'Bebida', 'verbose_name_plural': 'Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.RenameField(
            model_name='bebida',
            old_name='id_BebidaCocktailDB',
            new_name='BebidaCocktailID',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='id_IngredientCocktailDB',
            new_name='IngredientCocktailID',
        ),
        migrations.AlterField(
            model_name='bebida',
            name='imagen',
            field=models.ImageField(upload_to='bebidasImagenes/'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, default=None, related_name='mis_ingredientes', to='DrinksAndPeople.Ingrediente', verbose_name='Ingredientes'),
        ),
    ]
