# Generated by Django 3.2.9 on 2021-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinksAndPeople', '0002_auto_20211125_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='IngredientCocktailID',
            field=models.IntegerField(blank=True, null=None),
        ),
    ]
