# Generated by Django 3.2.9 on 2021-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinksAndPeople', '0003_alter_ingrediente_ingredientcocktailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='IngredientCocktailID',
            field=models.IntegerField(blank=True),
        ),
    ]
